apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}