apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.mongodb }}
    targetPort: 27017
    protocol: TCP
    name: {{ .Values.service.portName }}
  selector:
    app: mongodb