image:
  registry: docker.io
  repository: mongo
  tag: 6.0
  pullPolicy: IfNotPresent
useStatefulSet: false

replicaCount: 1

containerPorts:
  mongodb: 27017

service:
  type: ClusterIP
  portName: mongodb
  ports:
    mongodb: 27017

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources: {}